version: '3'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: infinity_box_qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=${WEBUI_PORT}
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./qbittorrent/config:/config
      - /root/Downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${WEBUI_PORT} || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

  filebrowser:
    image: filebrowser/filebrowser
    container_name: infinity_box_filebrowser
    user: "1000:1000"
    volumes:
      - /root/Downloads:/srv
      - ./filebrowser/database.db:/database.db
    ports:
      - "${FILE_SERVER_PORT}:80"
    restart: unless-stopped
    command: --root /srv --database /database.db
    healthcheck:
      test: ["CMD", "/filebrowser", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3