version: '3'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: infinity_box_qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=${QBT_WEBUI_PORT}
    ports:
      - "${QBT_WEBUI_PORT}:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./config:/config
      - /root/downloads:/downloads
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: infinity_box_filebrowser
    volumes:
      - /root/Downloads:/srv
      - ./filebrowser.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
    user: "${UID}:${GID}"
    ports:
      - "${FILEBROWSER_PORT}:80"
    restart: unless-stopped