version: '3'

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: infinity_box_qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=${WEBUI_PORT}
    ports:
      - "${WEBUI_PORT}:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./qbittorrent/config:/config
      - /root/downloads:/downloads
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: infinity_box_filebrowser
    volumes:
      - /root/Downloads:/srv
    user: "1000:1000"
    ports:
      - "${FILE_SERVER_PORT}:80"
    restart: unless-stopped